### PR TITLE
Basic a* integrity provided, small restructurization

### PR DESCRIPTION
**Pull request by michalshy**

### CODE REVIEW

**Comment by michalshy** [comment]
update, now grid considers agv size and agv is moving, although not accordingly to path

**Comment by michalshy** [comment]
update, drawing of help line works, path to follow provided into AGV class

**Comment by michalshy** [comment]
update, provide basic routing

**Comment by michalshy** [comment]
update: big restructure provided

**Review by yumitaru — APPROVED** [review]
nice!

**Review by Saesenthessis66 — APPROVED** [review]
nice job

**Pull request merged**
