### PR TITLE
Add Simpy and handle events, refactor functions to Pascal Case, variables to private

### PR DESCRIPTION
**Pull request by michalshy**
Add Simpy and handle events, refactor functions to Pascal Case, variables to private

### CODE REVIEW

**Review by Saesenthessis66 — COMMENTED** [review]
[Functions to PAscal Case] - hell naw...

**Review by yumitaru — APPROVED** [review]
bomba

**Review by Saesenthessis66 — CHANGES_REQUESTED** [review]
change wrong comment...!

**Review by yumitaru — APPROVED** [review]
klat

**Review by Saesenthessis66 — APPROVED** [review]
now we talkin

**Pull request merged**
